language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
env:
  - GOARCH=amd64
  - GOARCH=386
sudo: false
go_import_path: github.com/open-rsm/vr
before_install:
script:
  - ./travis.sh
notifications:
  email: false
